shap_calculator:
  val_inps_path: val_inps.csv
  model_path: #IM2Deep
  model_type: charge
  mode: charge1 #y0+1 for viz
  perm_path: #data/y5+1 Prosit2019/perm.txt # Path or leave empty to generate and save new permutation
  samp: 20
  bgd_sz: 5
shap_visualization:
  sv_path: data/y7+1/output.parquet.gzip
  clustering:
    from_which_end: left
    number_of_aa: 4
  filter_expr: 
