shap_calculator:
  val_inps_path: val_inps.csv
  model_path: Prosit_2019_irt
  model_type: koina
  ion: "rt" #y0+1 for viz
  perm_path: #data/y5+1 Prosit2019/perm.txt # Path or leave empty to generate and save new permutation
  samp: 200
  bgd_sz: 100
shap_visualization:
  sv_path: data/y7+1/output.parquet.gzip
  clustering:
    from_which_end: left
    number_of_aa: 4
#make it run with koina (maybe model path?)
