shap_calculator:
  val_inps_path: val_inps.csv
  model_path: Prosit_2019_intensity
  model_type: koina
  ion: y2+1
  perm_path: # Path or leave empty to generate and save new permutation
  samp: 200
  bgd_sz: 100
shap_visualization:
  sv_path: data/y2+1/output.parquet.gzip
  clustering:
    from_which_end: left
    number_of_aa: 5
