shap_calculator:
  val_inps_path: val_inps.csv
  model_path: saved_model/save_medium
  model_type: transformer
  ion: b3+1
  perm_path: # Path or leave empty to generate and save new permutation
  samp: 200
  bgd_sz: 100
shap_visualization:
  sv_path: b3+1/output.parquet.gzip
  clustering:
    from_which_end: right
    number_of_aa: 4
