shap_calculator:
  # SHAP calculation settings
  val_inps_path: "/cmnfs/home/j.lapin/projects/shabaz/data/uvpd_shap_input.csv"
  ion: x5
  perm_path: # Path or leave empty to generate and save new permutation
  samp: 200
  bgd_sz: 100
  
  # Reconstituting a saved torch model
  model_type: torch
  model_path: "/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-11-30_05-33-17/weights/model_epoch28_0.2856"
  ion_dict_path: "/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-11-30_05-33-17/filtered_ion_dict.csv"
  token_dict_path: "/cmnfs/data/proteomics/shabaz_exotic/processed/merged_search/UVPD/token_dictionary.txt"
  yaml_dir_path: "/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-11-30_05-33-17/yaml"
  
shap_visualization:
  ion: y5
  sv_path: "y5/output.parquet.gzip"
  clustering:
    run: False
    from_which_end: right
    number_of_aa: 6
