shap_calculator:
  # SHAP calculation settings
  output_dir: b7+1
  val_inps_path: "./val_inps.parquet"
  mode: b7+1
  perm_path: b7/perm.txt # Path or leave empty to generate and save new permutation
  samp: 200
  bgd_sz: 100
  inputs_ignored: 3 # Trailing attributes to ignore in input vector
  queries:
    - "peptide_length > 7"
    #- "method == 'HCD'"
  
  # Reconstituting a saved torch model
  model_type: koina
  model_path: "Prosit_2019_intensity" #"/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-12-13_16-05-52/weights/model_epoch26_-0.8569"
  ion_dict_path: "/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-12-13_16-05-52/filtered_ion_dict.csv"
  token_dict_path: "/cmnfs/data/proteomics/shabaz_exotic/processed/merged_search/allinone/token_dictionary.txt"
  yaml_dir_path: "/cmnfs/home/j.lapin/projects/shabaz/torch/save/2024-12-13_16-05-52/yaml"
  method_list: [ECD,EID,UVPD,HCD] # FIXME MUST BE SAME AS IN loader.yaml
  
shap_visualization:
  mode: b5+1
  sv_path: "UVPD_b5/output.parquet"
  filter_expr:
  clustering:
    run: False
    from_which_end: right
    number_of_aa: 6
